oa runs openacd with ~/oarun as rundir

diff --git a/bin/oa b/bin/oa
--- a/bin/oa
+++ b/bin/oa
@@ -1,8 +1,52 @@
 #!/bin/bash
 
-OPENACD_ROOT=/vagrant/OpenACD
-ERL=erl
+OPENACD_ROOT=~/workspace/openacd
+RUNDIR=~/oarun
+PLUGINDIR="$RUNDIR"/plugin.d
+DBDIR="$RUNDIR"/db
+LOGDIR="$RUNDIR"/log
 
+KEY="$RUNDIR"/key
+SYSCONFIG="$RUNDIR"/etc/sys.config
+
+ERL=erl
 NAME=openacd
 
-erl -name "$NAME" -s openacd -pa "$OPENACD_ROOT/ebin" -pa "$OPENACD_ROOT/deps/*/ebin" $*
+mkdir -p "$RUNDIR"
+mkdir -p "$DBDIR"
+mkdir -p "$PLUGINDIR"
+mkdir -p "$LOGDIR"
+
+export OPENACD_RUN_DIR="$RUNDIR"
+
+if [ ! -f "$KEY" ]; then
+	echo "RSA key does not exist, generating..."
+	ssh-keygen -t rsa -f "$KEY" -N ""
+	RES=$?
+	if [ $RES != 0 ]; then
+		echo "Key generation failed with error $RES!"
+		exit $RES
+	fi
+fi
+
+
+if [ ! -f "$SYSCONFIG" ]; then
+	mkdir -p `dirname $SYSCONFIG`
+
+	CONFIGNODENAME=`erl -eval "io:format(\"~s\",[node()]),halt(1)" -name $NAME -noshell`
+	cat > "$SYSCONFIG" <<EOF
+[{'OpenACD', [
+	{nodes, ['$CONFIGNODENAME']},
+	{console_loglevel, info},
+	{logfiles, [{"$LOGDIR/openacd.log", debug}]},
+	{plugin_dir, "$PLUGINDIR"}
+]},
+{sasl, [
+	{errlog_type, error} % disable SASL progress reports
+]}].
+EOF
+
+fi
+
+exec erl -name "$NAME" -pa "$OPENACD_ROOT/ebin" "$OPENACD_ROOT"/deps/**/ebin "$OPENACD_ROOT"/include_apps/**/ebin \
+	-mnesia dir \""$DBDIR"\" -config "$SYSCONFIG" -s openacd $*
